Feat/hero
unepwcmc/SUS-ORS pull request #2
Opened 2023-02-22 12:03 UTC by Maxycle

## Changes

| Type | Description |
| - | - |
| Feat | add/build hero |

### Comments

## Testing

### Steps

1. Clone the project
2. Open 2 tabs in your terminal, cd in nuxt-frontend in one tab, run `yarn install` and `yarn dev`
3. cd in rails-api in the other tab, run `bundle install` and `bundle exec rails s`
4. Go to localhost:8080

### Expectations

- Check that the Hero looks like in the design

## Links

**Design:** [Hero 1 Comp/Mockup](https://www.figma.com/file/Z0gaYRYxCpaakHoo4i5pMO/ORS-WEBSITE?node-id=1%3A53&t=VgIjphOWA81pq4Li-0)

**Codebase:** [58](https://unep-wcmc.codebasehq.com/projects/online-reporting-system-redesign/tickets/58)

2023-03-02 18:05 UTC, nym1k requested changes
Please can you also make sure the header navigation links are 14px with line height of 19px, as per the designs. You should also make sure that padding is not applied to the edges of the navigation using :first-child and :last-child psuedoclasses

2023-03-02 18:05 UTC, nym1k commented on nuxt-frontend/components/Frontend/Layout/Footer.vue
> +        <div class="bg-blue-font flex justify-center py-2 px-2 rounded-sm w-full font-semibold mt-3" v-text="buttonSupportCenterText" />
The text of this button should be 14px with a line height of 19px

2023-03-02 18:05 UTC, nym1k commented on nuxt-frontend/components/Frontend/Layout/Footer.vue
> +      <div class="text-black text-3xl pt-4">
The font here should be 34px with a 54.43px line height (Roughly 1.6 lineheight)

2023-03-07 11:48 UTC, Maxycle commented on nuxt-frontend/components/Frontend/Layout/Footer.vue
> +        <div class="bg-blue-font flex justify-center py-2 px-2 rounded-sm w-full font-semibold mt-3" v-text="buttonSupportCenterText" />
I have used `text-sm` tailwind class instead of giving custom values as it was almost the same 

text-sm | font-size: 0.875rem; /* 14px */ line-height: 1.25rem; /* 20px */
-- | --

2023-03-30 13:59 UTC, Joseph-Burke commented
I'm going to switch the base for this PR from `main` to `develop`, as per the Gitflow workflow

2023-03-30 14:39 UTC, Joseph-Burke approved these changes
Approving this PR conditional on one or two questions I've left @Maxycle 

If you just check them out before merging, that would be great :)

2023-03-31 13:06 UTC, Maxycle commented on nuxt-frontend/components/Frontend/Layout/Navigation/Menu.vue
>              v-text="link.name"
So `NuxtLink` is a component provided by `Nuxt`, not a component that we made, therefore we don't have access (at least not directly and easily) to the template. It's like an `a` tag basically. It works as expected.

2023-03-31 13:29 UTC, Maxycle commented on nuxt-frontend/components/Frontend/Icon/Logo.vue
I don't really have an answer. We could have a folder with SVGs and use them like this => `<img src="~assets/yourSVG.svg" />` and it works the same. It might be easier and quicker to have them in a `.vue` file when we write code => open a tag and then write `FIcon + name of your svg`. I have done this way because that's how Jono was doing. Happy to change if there is a good reason.

2023-04-03 13:30 UTC, Joseph-Burke commented on nuxt-frontend/components/Frontend/Icon/Logo.vue
Created a ticket to look into this: https://unep-wcmc.codebasehq.com/projects/online-reporting-system-redesign/tickets/159

2023-04-03 13:32 UTC, Joseph-Burke commented on nuxt-frontend/components/Frontend/Layout/Navigation/Menu.vue
>              v-text="link.name"
Seems from discussing with @Maxycle that NuxtLink has some functionality in Nuxt. And the v-text attribute is the proper way to pass the link's text content to the component, so this seems fine

2023-04-03 14:02 UTC, merged