Feat/account page
unepwcmc/SUS-ORS pull request #4
Opened 2023-02-22 12:09 UTC by Maxycle

## Changes

| Type | Description |
| - | - |
| Feat | add/build components for "My account" page |
| Feat | build "My account" page  |

### Comments

## Testing

### Steps

1. Clone the project
2. Open 2 tabs in your terminal, cd in nuxt-frontend in one tab, run `yarn install` and `yarn dev`
3. cd in rails-api in the other tab, run `bundle install` and `bundle exec rails s`
4. Go to localhost:8080, click on `My account` in the navbar

### Expectations

- Check the `Details` tab and check that it matches the design
- Check the `Contacts` and check that it matches the design 

## Links

**Design:** [MY ACCOUNT/Mockup](https://www.figma.com/file/Z0gaYRYxCpaakHoo4i5pMO/ORS-WEBSITE?node-id=309%3A5788&t=VgIjphOWA81pq4Li-0)

**Codebase:** [61](https://unep-wcmc.codebasehq.com/projects/online-reporting-system-redesign/tickets/61), [62](https://unep-wcmc.codebasehq.com/projects/online-reporting-system-redesign/tickets/62), [63](https://unep-wcmc.codebasehq.com/projects/online-reporting-system-redesign/tickets/63), [64](https://unep-wcmc.codebasehq.com/projects/online-reporting-system-redesign/tickets/64)

2023-03-02 18:30 UTC, nym1k requested changes
Changes needed

2023-03-02 18:30 UTC, nym1k commented on nuxt-frontend/components/Frontend/Account/Details.vue
> +    <div class="text-3xl mb-6">
This should be font size 24px with line height of 32.68px (Around 1.4 line height)

2023-03-02 18:30 UTC, nym1k commented on nuxt-frontend/components/Frontend/Account/ProfilePictureCard.vue
> +    <FButtonsButton
This button should have a font-size of 14px and line height of 19px. The padding should also be 10px by 18px. It shouldn't have a width applied to it. The font weight should also be 700, and the border width should be 1px not 2px.

2023-03-02 18:30 UTC, nym1k commented on nuxt-frontend/components/Frontend/Account/Details.vue
> +        <FFormInput label="First name" placeholder="Add your first name" />
Form labels should be font size 18px line height 25px, with a margin bottom of 12px. They should also be wrapped in label tags, not plain div tags.

2023-03-02 18:30 UTC, nym1k commented on nuxt-frontend/components/Frontend/Account/Details.vue
> +        <FFormInput label="First name" placeholder="Add your first name" />
Text in the inputs should be font size 14px and line height 19px, including the placeholder text. The inputs should not have a fixed height on them, and should have 14px padding on all sides instead.

2023-03-30 15:25 UTC, Joseph-Burke requested changes
This is really great stuff @Maxycle , I'm very impressed with your coding style.

The changes requested should be pretty self-explanatory. Let me know what you think to it all!

2023-03-30 15:25 UTC, Joseph-Burke commented on nuxt-frontend/components/Frontend/Account/ProfilePictureCard.vue
> +      Upload a profile picture. <br> Max size 2MB
I think we have a general rule not to use `<br>` and to instead put the text in another element whose positioning we then control with styling.

I think it might be an improvement here to replace the use of `<br>` with something else...

2023-03-30 15:25 UTC, Joseph-Burke commented on nuxt-frontend/components/Frontend/Icon/Contacts.vue
I commented on this in another PR, but does this need to be in a `.vue` file? Could we not just have it in an `.svg`, and likewise for `Delete.vue`, `Details.vue`, `Duplicate.vue`, `Edit.vue`, `Logo.vue`, etc.

I think it would make it clearer to people working on the project that these files don't contain 'true' components, just images. What do you think?

2023-03-30 15:25 UTC, Joseph-Burke commented on rails-api/config/initializers/cors.rb
> +    # origins Rails.application.credentials.dig(:cors, :origins).split(',').map(&:strip)
I'm presuming this is for development purposes.

If you're unsure of whether we want `origins '*'` to reach the production environment, then I recommend that we revert this file to its previous form, and we can put `origins '*'` in as a comment, with a comment explaining what it does and why it might be useful.

2023-04-03 09:20 UTC, Maxycle commented on nuxt-frontend/components/Frontend/Tabs/Tabs.vue
> +      return 'font-medium text-blue-font opacity-50 cursor-pointer'
That's correct and I feel the same, `data` is a better place for a string.

2023-04-03 09:25 UTC, Maxycle commented on rails-api/config/initializers/cors.rb
> +    # origins Rails.application.credentials.dig(:cors, :origins).split(',').map(&:strip)
It is for development purposes indeed. As we don't have any `cors` and `origins` keys in the creds yet, I had to use `*` to make the app work. It will not reach the production environment.

2023-04-03 13:36 UTC, Joseph-Burke commented on nuxt-frontend/components/Frontend/Icon/Contacts.vue
Already dealt with elsewhere

2023-04-03 13:42 UTC, merged